### ISSUE TITLE
Ability to specify default value for CheckBoxGroup

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet-designer#109]
Today, it is possible, for a CheckBox, to specify both a value (via Checked) and a default value (via DefaultChecked).

But, for a CheckBoxGroup, the value is specified via the nice dropdown selector and there is no corresponding way to select the default state of the group.  It would be nice to have a defaultValue selector similar to the value selector.

While making this change, can the defaultValue selector for a RadioButtonGroup be improved to have dropdown behavior instead of relying on the user typing in the text of a radio button option?  The existing value selector is nice, but the defaultValue is a clunky text input.

**Comment by ericsoderberghp** [comment]
Required https://github.com/grommet/grommet/pull/6331
