### ISSUE TITLE
SVG images

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet-designer#11]
This tool is not an SVG editor. But, it's helpful to allow richer background graphic images created as SVGs. SVG images are usually fairly compact, compared to JPEGs and PNGs. So, how about allowing the user to browse or drop a file on a Box background image property, or an Image src property? Restrict to SVG file types. Make it a data URI and include it in the design.

Another option would be to add an SVG component type. This could be used instead of an Image and would be useful for primary graphics, like Stak. This approach wouldn't work for Box backgrounds though.

**Comment by ericsoderberghp** [comment]
Added in 6dc29eaf0e48e6b08a5d2d631f47aa0d60170bd8

**Comment by basiltt** [comment]
Can you share an example of its usage ?
