### ISSUE TITLE
Add support for menu item grouping

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet-designer#111]
Can we get support for menu item grouping in Designer, as shown in the second example here?  
https://design-system.hpe.design/components/menu?q=menu#grouping

A design idea to consider: if I add a menu item of "-", it is interpreted as a separator and any link for that item is ignored.

**Comment by ericsoderberghp** [comment]
This is now available.
![Screen Shot 2022-10-20 at 8 57 01 AM](https://user-images.githubusercontent.com/11637956/196998845-96a62579-b56f-4ef1-8ed8-23ca35d2f0d1.png)
