### ISSUE TITLE
Screen goes blank when pressing Button inside Designer

### ISSUE THREAD

**Issue by Israel-Laguan** [grommet/grommet-designer#12]
# Description:
I've made a  design, but when adding a Button (blank, default), and pressing it or the name on Left Bar, the screen goes blank.

# My code:

`
{"screens":{"1":{"id":1,"root":2,"name":"SEO KeywordsTool"}},"screenOrder":[1],"components":{"2":{"id":2,"type":"Grommet","props":{"style":{"height":"100vh"}},"children":[3,12],"collapsed":false},"3":{"type":"Grid","id":3,"props":{"align":"center","alignContent":"center","justify":"center","columns":"xlarge"},"name":"LoginForm","children":[4,6,9]},"4":{"type":"Box","id":4,"props":{"align":"center","justify":"center","pad":"small","alignSelf":"center","animation":[{"type":"fadeIn","delay":5},{"type":"jiggle","delay":2}],"background":{"color":"brand"},"round":"medium"},"name":"Tiitle","children":[5]},"5":{"type":"Heading","id":5,"props":{"color":"accent-2"},"text":"Entra"},"6":{"type":"Box","id":6,"props":{"align":"center","justify":"center","pad":"small","overflow":"auto","wrap":true,"alignSelf":"start","background":{"color":"dark-1"},"round":"small","width":"large"},"name":"Email","children":[7,8],"collapsed":false},"7":{"type":"FormField","id":7,"props":{"color":"brand","error":"Revisa si el email esta bien escrito","help":"Trata de que no queden espacios antes, en medio, o despues del email.","label":"EMAIL"},"name":"email"},"8":{"type":"TextInput","id":8,"props":{"placeholder":"Ingresa tu email aca"},"name":"emailInput"},"9":{"type":"Box","id":9,"props":{"align":"center","justify":"center","pad":"small","background":{"color":"dark-1"},"wrap":true,"overflow":"auto","round":"small","width":"large"},"name":"Password","children":[10,11]},"10":{"type":"FormField","id":10,"props":{"error":"Verifica que tu password este bien escrito","help":"Trata de que no queden espacios antes, en medio o al final de tu contrasena","label":"CONTRASENA","color":"accent-2"},"name":"password"},"11":{"type":"TextInput","id":11,"props":{"placeholder":"Ingresa tu contrasena"},"name":"passwordInput"},"12":{"type":"Button","id":12,"props":{"label":"Button"}}},"nextId":13,"version":2}
`
Local Storage saves my design
![image](https://user-images.githubusercontent.com/36519478/59172765-7d08a680-8b0f-11e9-9e91-83a0e903ad13.png)

Console shows this message:
![image](https://user-images.githubusercontent.com/36519478/59172778-8db91c80-8b0f-11e9-99ba-e9489118123c.png)

# What is expected:

Nothing more than the normal hover/click Button animation

# What it happens:

The whole screen goes suddenly blank
# How to reproduce:

Save code into a JSON, upload to designer, click button. I've made the same several times in private or normal mode in Firefox ESR on debian 9, with the same result.

**Comment by ericsoderberghp** [comment]
Apologies for this issue. It turned out to be an issue with our CI/CD pipeline. :(
It should be working now.
