### ISSUE TITLE
Can't find fastest path to create a new document from scratch

### ISSUE THREAD

**Issue by jensy** [grommet/grommet-designer#17]
Expected behavior: File - New Document

**Comment by jensy** [comment]
OK I just found out that the Trash icon gives me that functionality, but that was not clear to me at all.

**Comment by ericsoderberghp** [comment]
Check the latest, where you can click the design name and "Reset" is the last option. Is this enough? Perhaps relabel it to something like "Start Fresh"?

**Comment by ericsoderberghp** [comment]
Happy to re-open if you are still having issues after the latest updates.
