### ISSUE TITLE
Lost all my work due to bug

### ISSUE THREAD

**Issue by jensy** [grommet/grommet-designer#22]
I do not fully remember what happened, but I dragged an anchor component into a button component (by accident) or something along these lines. The app showed me a blank page and it comes up after refreshing the page too.

![image](https://user-images.githubusercontent.com/105723/59882116-952dc080-936e-11e9-8991-9d9e3827eb5c.png)

Fortunately I took screenshots of my progress. 😥

Expected behavior: I don't know how to avoid bugs like this, but maybe snapshots of progress could be captured and retrieved somehow, even if you did not publish designs in a while.

**Comment by ericsoderberghp** [comment]
The commit above fixes a chunk of exceptions that we are now catching and allowing the user to undo the change. But, there could still be bugs that might be hard to recover from. Closing this to see what comes up next with more detail.
