### ISSUE TITLE
Bug with JS code being generated by Navigation Patterns | Grommet Designer

### ISSUE THREAD

**Issue by nrydevopswatch** [grommet/grommet-designer#47]
Today I noticed that there seems to be a bug with the JS code being generated with https://designer.grommet.io/

It is generating ```const Huband Spoke``` which is a variable declaration that can be done. The code compiled correctly once I removed the extra space from ```const HubandSpoke``` and similarly in the route, ```<Route path="undefined" Component={HubandSpoke} />```

Another possible issue is that once I compiled and ran the generated code is that clicking down on the bottom ```Patterns``` buttons ```Hub and Spoke``` ```Banner``` and ```Sidebar``` it does not switch between those components as it does on the online demo.

**Comment by ericsoderberghp** [comment]
Fixed an issue with the screen component name generation when exporting code. Also, updated the Navigation Patterns example to set paths so the routing works.
