### ISSUE TITLE
When I select a layer, jump to it in layers list

### ISSUE THREAD

**Issue by jensy** [grommet/grommet-designer#51]
Expected behavior (as learned in most design software) is that when you select a layer on the canvas, it will be reflected in the layer list too.

**Comment by jensy** [comment]
The issue occurs when your Screen is collapsed. Expected behavior is that the Screen layer expands and takes you to the relevant layer inside.

**Comment by ericsoderberghp** [comment]
Looks like this was fixed in 897d60158f48e07dfba4d23043185f2df73c3a8e.
