### ISSUE TITLE
Icon size in button component

### ISSUE THREAD

**Issue by jensy** [grommet/grommet-designer#52]
Changing the size property on a button with an icon does not apply anything.

<img width="519" alt="image" src="https://user-images.githubusercontent.com/105723/76903388-8f183200-6863-11ea-8255-869585fcb6c8.png">

**Comment by ericsoderberghp** [comment]
Well, that's how grommet works. Were you thinking that the icon should also scale up and down with the size?

**Comment by ericsoderberghp** [comment]
Changed the designer to automatically set the icon size when the Button is given a size. This will also apply to all other places where `icon` is a property, such as Menu.
