### ISSUE TITLE
New Design behavior

### ISSUE THREAD

**Issue by jensy** [grommet/grommet-designer#54]
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/105723/78189275-f7a00b00-742e-11ea-9b91-8c66c64dc7fe.png">

When you create a new design it will take the date as default title, if you keep hitting create new, it will overwrite the design if you did not change the name.

Suggestions
- Use Untitled as the default title
- If you did not change the title and you click New, create a new document Untitled (or Untitled 2, etc.)
- Alternatively, prompt the user to name their design when you click New

**Comment by jensy** [comment]
The prompt could bring up the modal where you change the name, pick a theme, etc. At least that's what I do always first anyway.

**Comment by ericsoderberghp** [comment]
Done as part of 08e44fdb2792b941641b17f79f18dfc8cec09202
