### ISSUE TITLE
Copy/paste properties

### ISSUE THREAD

**Issue by jensy** [grommet/grommet-designer#67]
It would be a great enhancement if I was able to copy/paste properties of a component, I do not always want to duplicate the whole component (maybe it has lots of children), but for example reusing a Box's properties for layout.

I can see it being added a shortcut, in Figma this is Cmd + Option + C/V or in the Component panel near the Duplicate action.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/105723/83028582-ddc61300-9fee-11ea-8c14-93886aa9bb31.png">

**Comment by ericsoderberghp** [comment]
Hmm... if done as a copy/paste, we'd have to restrict it to components of the same type.

I'm considering another approach where we add something to the component drop menu to "copy props from another <ComponentType>". This would then provide a picker to choose the existing component to copy the props from, relying on the name in the designer and allowing search for it.
