### ISSUE TITLE
Code generator error:  "false" or "undefined" is third generated line of code.

### ISSUE THREAD

**Issue by dgennetten** [grommet/grommet-designer#70]
Each of only about five or six code gen attempts has yielded either "false" or "undefined" as the third line of generated code after the import statements.  For me, this happens even with a simple two-page design with only button on each page.

**Comment by jjwilliams42** [comment]
It looks like on this line:

https://github.com/grommet/grommet-designer/blob/a78dcfd55cc86f7c93f5a6d751e0c3e230ae606f/src/design/code.js#L241

There probably needs to be an || '' at the end, otherwise if theme is undefined, it is generating undefined.
