### ISSUE TITLE
Hide empty data properties

### ISSUE THREAD

**Issue by jensy** [grommet/grommet-designer#81]
Currently, if a data prop is empty it will show the path notation, instead of nothing at all. I tried `null` and empty strings, but both show path notation.

See example here: https://designer.grommet.io/?id=API%252FJSON-mock-test-pentenrieder-hpe-com

Expected behavior is to show nothing + option to hide the wrapping component.

**Comment by ericsoderberghp** [comment]
Thanks for reporting. This has been fixed.
